version: 2.1

jobs:
  pytest:
    parameters:
      cluster_type:
        type: string
    machine:
      image: ubuntu-2004:202104-01
      docker_layer_caching: true
    environment:
      CLUSTER_TYPE: << parameters.cluster_type >>
      CIAB_IMAGE: << parameters.ciab_image >>
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y apt-transport-https
            sudo apt-get update
            sudo apt-get install -y mariadb-client-core-10.3 python3 python3-virtualenv
            virtualenv .env3 -p /usr/bin/python3
            source .env3/bin/activate
            pip install .
            pip install -r dev_requirements.txt
      - run:
          name: Start SingleStore cluster and run integration tests
          command: |
            ./.circleci/run-tests.sh

workflows:
  test:
    jobs:
      - pytest:
          name: "Managed Service connection test"
          matrix:
            parameters:
              cluster_type: 
                - s2ms
              ciab_image:
                - none, because it's s2ms cluster
      - pytest:
          name: "SingleStore 8.1 connection test"
          matrix:
            parameters:
              cluster_type:
                - ciab
              ciab_image:
                - singlestore/cluster-in-a-box:alma-8.1.1-45eec847e2-4.0.11-1.16.0
      - pytest:
          name: "SingleStore 8.5 connection test"
          matrix:
            parameters:
              cluster_type: 
                - ciab
              ciab_image:
                - singlestore/cluster-in-a-box:alma-8.5.16-21d309f57c-4.0.17-1.17.10

